### ISSUE TITLE
4* Animation plays for 5* pulls

### ISSUE THREAD

**Issue by MidKnight7** [uzair-ashraf/genshin-impact-wish-simulator#1]
It looks like there is no change in the animation when you pull a 5*.  If possible, could you code that in?

**Comment by muazamkamal** [comment]
I think the author didn't have a clean footage of a 5 stars pull. 

I do have a 5 stars pull footage, but it's a single pull footage (just 1 comet thingy), I can provide that if the author wants it.

**Comment by uzair-ashraf** [comment]
@muazamkamal Sorry but I want to keep the footage to 10 stars, but I really do appreciate the offer, I'll try to strip it from a youtube video tonight and incorporate it.

**Comment by MidKnight7** [comment]
If possible, the pull sounds being incorporated would be amazing, but no issues if it is going to be a pain.  I don't believe that the 4* and 5* pulls have a different sound but I could be wrong

**Comment by uzair-ashraf** [comment]
It has been added gents!
