### ISSUE TITLE
Meta Title & Image Not Showing

### ISSUE THREAD

**Issue by testerslol123** [uzair-ashraf/genshin-impact-wish-simulator#15]
I'm open this because this repo doesn't has any of image or title when share to media social platform like facebook / twitter.

And pull request is ready to take on that issue. #14 

Thank you @uzair-ashraf

**Comment by uzair-ashraf** [comment]
Sorry @testerslol123 Webpack now dynamically generates the meta tags, so your pr will require a refactor
