### ISSUE TITLE
Banner changed to Beginner Wish after reset and pulling again on the same banner

### ISSUE THREAD

**Issue by TaurusNova** [uzair-ashraf/genshin-impact-wish-simulator#17]
There is an issue when i was rolling on Klee's, Weapon and Standard Banner.
After doing roll, i was intended to reset the banner. Then, i proceed to rolling again on the same banner. I noticed that, the banner immediately changed to Beginner Wish.

**Comment by lauslim12** [comment]
Hello!

I have successfully replicated the bug. It seems that after we clicked the reset button and decided to roll again, the banner will return to Beginner's Wish, not the currently selected banner.

I will drop a fix soon in the form of a PR. Thank you!

**Comment by TaurusNova** [comment]
Glad to hear that, thanks for your hardwork!

**Comment by TaurusNova** [comment]
Thank you so much dude!
