### ISSUE TITLE
Best Idea Training Room

### ISSUE THREAD

**Issue by DemonRem** [uzair-ashraf/genshin-impact-wish-simulator#20]
hey @uzair-ashraf 
i have idea for you what about to add function to the simulator that you can check and practice with the character gameplay and switch between elements to be more pro and learn the character mech
if you can add that its be amazing.
thank for reading that

**Comment by uzair-ashraf** [comment]
So a training room to test out characters?
@DemonRem the concept is very cool! However I don't believe it will be possible with the current systems setup.  We can only do so much in the browser 😅
