### ISSUE TITLE
There is a problem with the weapon pool algorithm

### ISSUE THREAD

**Issue by birdy0017** [uzair-ashraf/genshin-impact-wish-simulator#22]
After more than 90 draws, 5 stars will be awarded

**Comment by uzair-ashraf** [comment]
Like constantly there is only 5 stars? or a guaranteed 5 star? That is how the pity system works.

**Comment by birdy0017** [comment]
After 18 times, 5 stars appeared 6 times in a row.

**Comment by uzair-ashraf** [comment]
I'll take a look in this update.

**Comment by uzair-ashraf** [comment]
The new update has been released, I don't notice the bug, @birdy0017 can you give it a shot and let me know?

**Comment by birdy0017** [comment]
![clipboard_20201113_125943](https://user-images.githubusercontent.com/50571479/99030606-6d1cae00-25b0-11eb-8e2c-afe61febb26e.png)
Starting from the 32nd time, five-star weapons will be released every 10 consecutive times.

**Comment by uzair-ashraf** [comment]
Ok! I'll be adding some integration tests, hopefully the cause will be more clear after that.  Thank you!
