### ISSUE TITLE
Banner gets eaten by carousel when over 1600px in width

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#26]
Need to set a max width on the container for the banners screen in order to keep the banner from being eaten up.  Looks weird on very wide screens.

Need to make sure elements stay centered as well.

**Comment by lauslim12** [comment]
Hey dude, can I work on this one?

**Comment by uzair-ashraf** [comment]
Oh dude please!

**Comment by lauslim12** [comment]
Done dude!
