### ISSUE TITLE
4-Star and 5-Star probability balancing between Character and Weapons

### ISSUE THREAD

**Issue by asmoranomar** [uzair-ashraf/genshin-impact-wish-simulator#28]
According to the standard banner:
Base probability of winning 5-star item = 0.600%.
Base probability of winning 5-star character = 0.300%.
Base probability of winning 5-star weapon = 0.300%.

Base probability of winning 4-star item = 5.100%.
Base probability of winning 4-star character = 2.550%.
Base probability of winning 4-star weapon = 2.550%.

It only seems like the first case is coded, but not the second or third (respectively).  Since there are more weapons than characters, leaving this as is will pull more weapons on average when a 4 or 5 star is pulled.  When a 5-star or 4-star is pulled, there should be an equal chance for either character or weapon.

Recommend: 
Separate functions for drawing character & weapon (perhaps similar to how getRandomFeaturedItem works).  
Implement flipACoin to determine whether one or the other is drawn when a successful 4 & 5 star is triggered.

Edit:
This also affects 4-star drops on featured banners.  When the 4-star is NOT the featured item, it acts similarly to the above.

Character banner:
Base probability of winning 4-star item = 5.100%.
Base probability of winning 4-star character = 2.550%.
Base probability of winning 4-star weapon = 2.550%.

Weapon banner:
Base probability of winning 4-star item = 6.000%.
Base probability of winning 4-star character = 3.000%.
Base probability of winning 4-star weapon = 3.000%.

**Comment by uzair-ashraf** [comment]
That is correct, they have added this in the new update, will need to add to the new banners as well.  Would you like to take this on? @asmoranomar

**Comment by asmoranomar** [comment]
I wish I was as talented.  I drive from over the shoulder - I'm only ok at reading code, but I have no confidence in writing code and I can never figure out how to work git.  I put effort in trying to explain my findings, so the knowledgeable can identify and verify them.  So, if anyone has questions I'd be happy to point out in more detail - but otherwise I'm happy to cheer you on.

**Comment by lauslim12** [comment]
If I see the code correctly, we might only need to add some adjustments (as described in the issue) to the `getRandomItem` function, as it is the code that is responsible for getting either weapon or character.

I can take this on, if you want me to.
