### ISSUE TITLE
Featured 4-star character guarantee not working

### ISSUE THREAD

**Issue by SignificantMaybe** [uzair-ashraf/genshin-impact-wish-simulator#37]
In the game, on the limited banners, if you pull a 4-star weapon/character that is not one of the featured weapons/characters, the next 4-star is guaranteed to be one of the featured weapons/characters. This feature is either not implemented or not working on this simulator, as I can often receive multiple non-featured items in a row.

**Comment by uzair-ashraf** [comment]
Which banner did you encounter this bug?

**Comment by SignificantMaybe** [comment]
Both current limited banners, the "Gentry of Hermitage" and the "Epitome Invocation". Here are some screenshots of what should be impossible pulls, the first from the Zhongli banner and the second from the weapon banner.
![sim-bug-zhongli-banner](https://user-images.githubusercontent.com/75646585/101419049-d42e3980-38b4-11eb-943e-c65e725840c3.png)
![sim-bug-weapon-banner](https://user-images.githubusercontent.com/75646585/101419051-d4c6d000-38b4-11eb-8003-74e2ad71c460.png)

**Comment by uzair-ashraf** [comment]
So the way the system is currently setup, is that if you get a 4 star character, and it is not a featured item, then your next one is guaranteed to be featured, but it can still randomly be a featured one as well.  Is that incorrect?

**Comment by SignificantMaybe** [comment]
I think what you said is correct, but that's not what I'm seeing in the sim. You shouldn't be able to get multiple non-featured 4-stars in a row. As in, it shouldn't be possible to get a Sucrose and an Eye of Perception without getting a Razor, Chongyun, or Xinyan in between them on the current limited banner. This applies to both pulls that are randomly 4-star and pulls that are guaranteed to be 4-star or higher.

**Comment by uzair-ashraf** [comment]
Ahhhh I see I see, alright, this will be added to the queue
