### ISSUE TITLE
Can you make a Chinese version

### ISSUE THREAD

**Issue by GengGode** [uzair-ashraf/genshin-impact-wish-simulator#46]
Hope to make a Chinese version, from Chinese players

**Comment by uzair-ashraf** [comment]
Feel free to! Were you the one I spoke to through email?

**Comment by GengGode** [comment]
应该不是，这是我们第一次通过电子邮件进行沟通。
I don't think so. This is the first time we communicate through e-mail.
翻译来自百度
Translation from Baidu

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用
