### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by MePsyDuck** [uzair-ashraf/genshin-impact-wish-simulator#47]
Although the simulator is supposed to be as close to actual game as possible, but I think few QOL improvements can be made:

1. Starting with preset pity counter
2. Show pity counter in the UI
3. Show past and future event banners
4. Have a skip animation button

**Comment by uzair-ashraf** [comment]
@MePsyDuck There is a skip animation button

**Comment by MePsyDuck** [comment]
There is a button, but you have to click it everytime. I was asking for a checkbox so that it is skipped everytime .

**Comment by uzair-ashraf** [comment]
Ah gotcha , there is plenty to do and most of these things can be added. It's just a matter of time due to my hectic work schedule.
