### ISSUE TITLE
I got a character from the weapon banner

### ISSUE THREAD

**Issue by calispeng** [uzair-ashraf/genshin-impact-wish-simulator#55]
I'd just hit pity on all 3 banners but for the weapon banner I also got 2 Razors. 
![Screenshot_20210124_031427_com android chrome](https://user-images.githubusercontent.com/77908521/105620285-402c1900-5df3-11eb-8d1e-09187526861c.jpg)

Best of luck and thanks so much!

**Comment by uzair-ashraf** [comment]
You can pull characters in the weapons banner, check the details page

and no worries!
