### ISSUE TITLE
Feature Request: Wish Counter on Banners

### ISSUE THREAD

**Issue by jay5656** [uzair-ashraf/genshin-impact-wish-simulator#56]
It's been asked already, but to show demand, I'd really like a counter to show how many times I've wished on a banner.

**Comment by uzair-ashraf** [comment]
## Adding a wish counter to each banner

## Problem

Users would like to know exactly, how many times they have already wished on a banner. The data is already there to be able to handle the pity system internally, so theoretically this should be straight forward to implement.

## Plan

1. Store the wish attempts inside of state
1. Create a helper method, that can force the attempts counts to sync up with state, everytime the following happens:
    - User wishes 10 times
    - User wishes one time
    - User loads data
1. Integrate the new settings system with the wish counter
1. Add integration tests to monitor user wish counts.
1. Update unit test

**Comment by uzair-ashraf** [comment]
Feature update is ready to go, need to update integration tests with dealing with a possible bug in banner slide generation
