### ISSUE TITLE
Feature request: historical banners 

### ISSUE THREAD

**Issue by bp968** [uzair-ashraf/genshin-impact-wish-simulator#66]
Forgive me if this has already been requested, but being able to show previous banners would add to the theory crafting fun.  Im thinking of a scenario where you give yourself X-cash and then see if you could have snagged your "perfect team" if you'd been around for those banners (klee, venti, etc).  

Again, forgive me if the functionality already exists and just isn't available on the live version.

**Comment by uzair-ashraf** [comment]
Rolling on previous banners will be added, its just a matter of me finding the time to do it properly.
