### ISSUE TITLE
More feature requests

### ISSUE THREAD

**Issue by 100beeep** [uzair-ashraf/genshin-impact-wish-simulator#78]
A couple more feature requests.
1.) Can you please add the Tartaglia rerun?  You’ll probably get there eventually, just a reminder.
2.) I’d love to see other weapon banners.
3.) A build your own banner.  The user inputs that characters/weapons, and pulls on it like they would a normal banner.
Thanks!

**Comment by uzair-ashraf** [comment]
I didn't know  Tartaglia rerun was out ehe, I'll do it this weekend

**Comment by uzair-ashraf** [comment]
I like the build your own banner idea, that's pretty sweet. I'll think about that one

**Comment by 100beeep** [comment]
Thanks!
Any news on the old weapon banners?  I'd really like that.
As a F2P, I don't wish on the weapons, so it adds something for me.
Thanks!
