### ISSUE TITLE
Update README.md with new features

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#8]
Since the updates requested on reddit there have been new features added
Please update the readme with the following features
- User can reset inventory
- User can see 5 star animation for 5 star pulls
- User can filter between characters, weapons, and ratings in inventory
- User can preserve the banner they wished for

**Comment by NathanPang001** [comment]
Hello, can I work on this?

**Comment by NathanPang001** [comment]
Sorry, this was a quick fix so I went ahead an worked on it. I also wanted to ask if I could help you add the images for the "Sparkling Steps" wish event and the next "Epitome Invocation" wish event into the [images/banner](https://github.com/uzair-ashraf/genshin-impact-wish-simulator/tree/master/src/assets/images/banners) when they come out.
