### ISSUE TITLE
v 1.6.1 no main js file

### ISSUE THREAD

**Issue by Hetystars** [uzair-ashraf/genshin-impact-wish-simulator#92]
the version of v1.6.1 has updated，but there is no js file for v1.6.1 @lauslim12 @elebitzero @uzair-ashraf @NathanPang001

**Comment by uzair-ashraf** [comment]
Can you add a screenshot of your error? And is it in production?

**Comment by uzair-ashraf** [comment]
Oh wait, you want to branch from staging not master
